// <auto-generated />
namespace BackCountryFreedom.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateModelsViewModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateModelsViewModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201712132259235_updateModelsViewModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
